# Generated by Django 5.2 on 2025-04-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_date',
            new_name='question_text',
        ),
    ]
